### ISSUE TITLE
User entity username 관련

### ISSUE THREAD

**Issue by youcastle03** [kakao-tech-campus-2nd-step3/Team2_BE#45]
User entity에서 현재 username이 nullable로 되어있습니다.
하지만 로그인을 카카오로 구현하다 보니 username을 초기값으로 넣을 방법을 고민중이라 일단 nullable을 제거하고 사용하였습니다

현재는 카카오 로그인을 하면 카카오 유저id를 저희의 userid로 사용하고 있습니다.
비즈앱이아니라 이메일등을 전달받을수 없기 때문인데 따라서 비즈앱으로 전환하고 사용자이름으로 username을 초기값으로 지정할지 아니면 현재처럼 로그인후 default_user라는 이름으로 유저네임을 기본값으로 할당하고 수정 홈페이지에서 수정하게 진행할지 어느 방향이 나을까요?

**Comment by peacefullyquietly** [comment]
추후에 키워드 알림이라던지, 리뷰에 판매자의 댓글이 달렸을 경우 알람 설정과 같이 카톡과 연관된 기능들을 추가적으로 이용하려면 비즈앱으로 전환 후 보다 많은 기능을 활용하는 것이 조금 더 효율적이라고 생각이 되긴합니다!

**Comment by jjh4450** [comment]
저도 비즈앱 도입에 찬성합니다만
