### ISSUE TITLE
[Fix] api 문서와 dto response가 맞지 않습니다!

### ISSUE THREAD

**Issue by dandamdandam** [kakao-tech-campus-2nd-step3/Team2_BE#91]
[UserInfoResponseDto](https://github.com/kakao-tech-campus-2nd-step3/Team2_BE/blob/main/src/main/java/jeje/work/aeatbe/dto/user/UserInfoResponseDto.java)

![image](https://github.com/user-attachments/assets/9797fd02-9420-46f4-89a5-a7ae931f0df7)

예시로 UserInfoResponseDto가 있는데, api 문서와 맞지 않는 부분이 꽤 있습니다.

특히 snake case naming 부분이 다 camel case 로 되어 있는 것 같습니다. 확인해주세요!

**Comment by jjh4450** [comment]
백엔드 코드 컨벤션이 camelCase로 되어 있어 API 문서를 수정해야 할 것 같습니다. 수정 전까지 모든 key값은 암묵적으로 카멜케이스 를 이용 부탁드립니다.

**Comment by humpose** [comment]
수정 했습니다!
